### ISSUE TITLE
Hi Owl Masters -- need some guidance with data persistence (or not?)

### ISSUE THREAD

**Issue by annalexc** [annalexc/cheesy#1]
NASA's API has a rate limit of 1000 calls per hour, which is generous, but a single search query from my app can potentially make 100 calls. Just wanted to talk through my query approach and if it would make more sense for me to save data into a JSON file to be rendered, or create an API to save query data to, limit my search, etc.

**Comment by ajhofferber** [comment]
Hey Anna. Are you still working on this blocker?

**Comment by annalexc** [comment]
Hey Ash -- nope, all resolved. Thanks :) :octocat:
